### ISSUE TITLE
Client timeout values expressed in incorrect units

### ISSUE THREAD

**Issue by ghost** [smartystreets/smartystreets-ruby-sdk#12]
It seems like the value passed in to the client builder falls right through to `Net::HTTP`, which interprets that number in seconds:

https://github.com/smartystreets/smartystreets-ruby-sdk/blob/master/lib/smartystreets_ruby_sdk/native_sender.rb#L19

![35660413-b2d469fe-06c0-11e8-99db-766346ae2598](https://user-images.githubusercontent.com/28246791/35660956-fc579fc6-06c3-11e8-80a6-d630739b3fba.png)

That makes the default timeout over two hours 😬

**Comment by MouaYing** [comment]
@Nathan-Brandless - Yikes! Good catch. We will look into this posthaste.

**Comment by MouaYing** [comment]
@Nathan-Brandless - A new version (v5.3.0) has just been released, and it includes a fix for this. 

Thanks for helping us find this!
