### ISSUE TITLE
Rails logger requires 1..3 arguments

### ISSUE THREAD

**Issue by MattWalston** [smartystreets/smartystreets-ruby-sdk#2]
This appears to be a 2.0 regression in CoreClientBuilder's initializer.

**Comment by MouaYing** [comment]
We have our own Logger class. It must be assuming we are creating an instance of a different Logger class. Sounds like a patch is in order.

**Comment by MattWalston** [comment]
Sounds about right.  I reverted as I’m busy right now but will take a stab
at it when I have some time.

**Comment by MouaYing** [comment]
@MattWalston It should be fixed now. Try v2.0.1.

**Comment by MattWalston** [comment]
Resolved.
