### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by BAlaji1453** [smartystreets/smartystreets-ruby-sdk#23]
<select id="advert_type_select" class="form-control" name="advert_types_name" multiple="true">
        <option value="">Select</option>
        **<% @adverts.each do |advert| %>**
          <option value="<%= advert.id %>"><%= advert.name %></option>
        <% end %>
      </select> 

- Method error in this particular loop  line. I dont know how its happening, please anyone explain me or give an right solution

**Comment by mdwhatcott** [comment]
I don't recognize that line of code as being part of this project (smartystreets-ruby-sdk). Could you provide more detail and confirm that this is actually an issue pertaining to this project?

**Comment by DuncanBeutler** [comment]
We recently merged a pull request in the `international-street-api` that looked very similar to the title of this issue. We will therefore be closing this issue. If you feel the issue has not been appropriately addressed, feel free to reopen this issue with further details regarding the nature of your specific issue. Thank you for using the `smartystreets-ruby-sdk`!
