### ISSUE TITLE
Unable to set candidates to 1 while using enhanced lookup

### ISSUE THREAD

**Issue by seand7565** [smartystreets/smartystreets-ruby-sdk#32]
Due to [this line](https://github.com/smartystreets/smartystreets-ruby-sdk/blob/f703786c645e92f7dd28bfb0c8b7c72bce0241ce/lib/smartystreets_ruby_sdk/us_street/client.rb#L50) (from [this commit](https://github.com/smartystreets/smartystreets-ruby-sdk/commit/834f9758e8e62d86fcef1835f2f0f258e6d5442f) for context) it's impossible to set your candidates to 1 while using enhanced matching.

It looks like the intention of the line is to set candidates to `5` if you're using enhanced matching and are using the default option for candidates in lookups ([which is also 1](https://github.com/smartystreets/smartystreets-ruby-sdk/blob/f703786c645e92f7dd28bfb0c8b7c72bce0241ce/lib/smartystreets_ruby_sdk/us_street/lookup.rb#L15)) but there are cases in which you would legitimately want 1 candidate with enhanced matching.

**Comment by DuncanBeutler** [comment]
This issue has been addressed on version 5.14.7. Thanks for catching that bug!
