### ISSUE TITLE
InternationalStreet::Lookup class is not being included automatically

### ISSUE THREAD

**Issue by mike-ball** [smartystreets/smartystreets-ruby-sdk#8]
I'm including the gem in a rails app. I can use all of the classes except SmartyStreets::InternationalStreet::Lookup.

All of this code works perfectly.
`credentials = SmartyStreets::StaticCredentials.new(auth_id, auth_token)`
`client = SmartyStreets::ClientBuilder.new(credentials).build_us_zipcode_api_client`
`lookup = SmartyStreets::USZipcode::Lookup.new`
and also
`client = SmartyStreets::ClientBuilder.new(credentials).build_international_street_api_client`

But, when I call `lookup = SmartyStreets::InternationalStreet::Lookup.new("A0A 0A2", 'Canada')`
I get the error message:
NameError: uninitialized constant SmartyStreets::InternationalStreet::Lookup

I found that if I manually require that file first, it will work. But not without requiring it first.
`require 'smartystreets_ruby_sdk/international_street/lookup'`

**Comment by MouaYing** [comment]
Thank you for letting us know! This problem will be fixed in the next release.
